---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN

image:
  name: ghcr.io/gohugoio/hugo:v0.164.0
  entrypoint: [""]

stages:
- deploy

before_script: |
  apk update
  apk add --no-cache bash npm curl
  node --version
  npm install -g wrangler@latest

deploy:
  stage: deploy
  script: |
    bash ./deploy.sh -d

  only:
  - main
  - more

